# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbtempo < Formula
  desc "Database performance monitoring and query analysis CLI"
  homepage "https://dbtempo.com"
  version "0.0.1771"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbtempo/releases/releases/download/v0.0.1771/dbtempo_darwin_x86_64.tar.gz"
      sha256 "95eeba2781207cd07692b8a252ae7fa23c0da3dd498840ea0af2a8e036530fd3"

      define_method(:install) do
        bin.install "dbtempo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbtempo/releases/releases/download/v0.0.1771/dbtempo_darwin_arm64.tar.gz"
      sha256 "393f6488eac4501d4d8cc7b754e08737d68b53ebbc9c370c18130d1554d1997f"

      define_method(:install) do
        bin.install "dbtempo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbtempo/releases/releases/download/v0.0.1771/dbtempo_linux_x86_64.tar.gz"
      sha256 "9338102a5d4409396dbeda8bb407e5a0b0a0576abe86df61e37ac2dfa44ec219"
      define_method(:install) do
        bin.install "dbtempo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbtempo/releases/releases/download/v0.0.1771/dbtempo_linux_arm64.tar.gz"
      sha256 "df0ad60a883e5f4a5a831910732de2a34fdd81ff014502d853af01375c5d05c4"
      define_method(:install) do
        bin.install "dbtempo"
      end
    end
  end

  service do
    run [opt_bin/"dbtempo", "daemon"]
    keep_alive crashed: true
  end

  test do
    system "#{bin}/dbtempo version"
  end
end
